name: Build Docker Image

on:
  push:
    branches:
      - develop
    paths:
      - 'docker/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set tag to the latest commit sha if this is a pull request
      - name: Set image tag
        id: image-tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "image_tag=ghcr.io/${{ env.OWNER_LC }}/sysrv-dev:${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=ghcr.io/${{ env.OWNER_LC }}/sysrv-dev:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.image-tag.outputs.image_tag }}
